// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxULeteoCQXXJYsklEE2DYoqYo2y4pvVI',
    appId: '1:1092043969695:web:825d0632b854981b56beaa',
    messagingSenderId: '1092043969695',
    projectId: 'sample-cc826',
    authDomain: 'sample-cc826.firebaseapp.com',
    storageBucket: 'sample-cc826.firebasestorage.app',
    measurementId: 'G-MS66RB1G6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB32fWQlmLTjY6iAv_zYMbYjGM1uTwpDtk',
    appId: '1:1092043969695:android:513968b085b65c2756beaa',
    messagingSenderId: '1092043969695',
    projectId: 'sample-cc826',
    storageBucket: 'sample-cc826.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6kObmgEIf9jDXPSl9plT7tym8kBgt854',
    appId: '1:1092043969695:ios:655b877a7ccb0e7f56beaa',
    messagingSenderId: '1092043969695',
    projectId: 'sample-cc826',
    storageBucket: 'sample-cc826.firebasestorage.app',
    iosBundleId: 'com.example.plantcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6kObmgEIf9jDXPSl9plT7tym8kBgt854',
    appId: '1:1092043969695:ios:655b877a7ccb0e7f56beaa',
    messagingSenderId: '1092043969695',
    projectId: 'sample-cc826',
    storageBucket: 'sample-cc826.firebasestorage.app',
    iosBundleId: 'com.example.plantcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxULeteoCQXXJYsklEE2DYoqYo2y4pvVI',
    appId: '1:1092043969695:web:41cd0caa387c2e2756beaa',
    messagingSenderId: '1092043969695',
    projectId: 'sample-cc826',
    authDomain: 'sample-cc826.firebaseapp.com',
    storageBucket: 'sample-cc826.firebasestorage.app',
    measurementId: 'G-1M3B591G3J',
  );
}
